spring:
  zipkin: 
    base-url: http://localhost:9411
  sleuth:
    sampler: 
      percentage: 1
  datasource:
    url: jdbc:mysql:///demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/
  instance:
    prefer-ip-address: true
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5 
mybatis:
  type-aliases-package: com.lenovo.t2t3.production.entity
security:
  basic:
    enabled: true
  user:
    name: admin
    password: qaz?123
